@startuml シーケンス図
actor "ユーザ" as u
boundary "ブラウザ" as b
control "web.php" as wp
control "Jissyu6_1Controller" as jc
entity "Person" as p
boundary "index.blade.php" as ibp
boundary "show.blade.php" as sbp
u -> b :該当ページをリクエスト[/jissyu13]
b -> wp :GET[/jissyu13]
wp -> jc :@index
jc -> p :all()
jc <-- p
jc -> ibp
u -> b :検索ボタンを押下
b -> wp :GET[/jissyu13/find]
wp ->jc :@find
jc -> p :where()->first()
jc <-- p
jc -> sbp
@enduml